-- Create reading_history table
create table if not exists public.reading_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  book text not null,
  chapter integer not null,
  words_read integer default 0,
  duration_seconds integer default 0,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for reading_history
alter table public.reading_history enable row level security;

-- Policies for reading_history
create policy "Users can view their own history"
  on public.reading_history for select
  using (auth.uid() = user_id);

create policy "Users can insert their own history"
  on public.reading_history for insert
  with check (auth.uid() = user_id);

-- Create saved_wisdom table (if missing)
create table if not exists public.saved_wisdom (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text not null,
  source text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for saved_wisdom
alter table public.saved_wisdom enable row level security;

-- Policies for saved_wisdom
create policy "Users can view their own wisdom"
  on public.saved_wisdom for select
  using (auth.uid() = user_id);

create policy "Users can insert their own wisdom"
  on public.saved_wisdom for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own wisdom"
  on public.saved_wisdom for delete
  using (auth.uid() = user_id);
