-- =====================================================
-- Feature Requests and Voting Tables
-- =====================================================

-- Create features table
create table if not exists public.features (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  status text default 'pending' check (status in ('pending', 'planned', 'in-progress', 'completed', 'declined')),
  category text default 'general' check (category in ('general', 'reading', 'highlights', 'ui', 'sync', 'other')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create feature_votes table (junction table for many-to-many)
create table if not exists public.feature_votes (
  id bigint generated by default as identity primary key,
  feature_id bigint references public.features(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  -- Ensure one vote per user per feature
  unique(feature_id, user_id)
);

-- Create indexes for performance
create index if not exists features_user_id_idx on public.features(user_id);
create index if not exists features_status_idx on public.features(status);
create index if not exists features_created_at_idx on public.features(created_at desc);
create index if not exists feature_votes_feature_id_idx on public.feature_votes(feature_id);
create index if not exists feature_votes_user_id_idx on public.feature_votes(user_id);

-- Enable RLS
alter table public.features enable row level security;
alter table public.feature_votes enable row level security;

-- Features policies
-- Anyone can view features
create policy "Anyone can view features"
  on public.features for select
  using (true);

-- Authenticated users can insert their own features
create policy "Authenticated users can insert features"
  on public.features for insert
  with check (auth.uid() = user_id);

-- Users can update their own features
create policy "Users can update their own features"
  on public.features for update
  using (auth.uid() = user_id);

-- Users can delete their own features
create policy "Users can delete their own features"
  on public.features for delete
  using (auth.uid() = user_id);

-- Feature votes policies
-- Anyone can view votes (to count them)
create policy "Anyone can view votes"
  on public.feature_votes for select
  using (true);

-- Authenticated users can vote
create policy "Authenticated users can vote"
  on public.feature_votes for insert
  with check (auth.uid() = user_id);

-- Users can remove their own votes
create policy "Users can remove their own votes"
  on public.feature_votes for delete
  using (auth.uid() = user_id);

-- Create view for features with vote counts
create or replace view public.features_with_votes as
select 
  f.*,
  coalesce(count(v.id), 0)::int as vote_count,
  array_agg(v.user_id) filter (where v.user_id is not null) as voter_ids
from public.features f
left join public.feature_votes v on f.id = v.feature_id
group by f.id;
