-- Create highlights table if it doesn't exist
create table if not exists public.highlights (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  book text not null,
  chapter integer not null,
  verse integer not null,
  color text not null,
  content text not null,
  note text, -- Ensure note column exists
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add note column if it doesn't exist (idempotent)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'highlights' and column_name = 'note') then
    alter table public.highlights add column note text;
  end if;
end $$;

-- Enable RLS
alter table public.highlights enable row level security;

-- Policies
create policy "Users can view their own highlights"
  on public.highlights for select
  using (auth.uid() = user_id);

create policy "Users can insert their own highlights"
  on public.highlights for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own highlights"
  on public.highlights for update
  using (auth.uid() = user_id);

create policy "Users can delete their own highlights"
  on public.highlights for delete
  using (auth.uid() = user_id);
